version: "3.8"
services:
  db:
    image: postgres:16
    container_name: commerce-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commerce
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7
    container_name: commerce-redis
    ports: ["6379:6379"]
    volumes: [redis_data:/data]

  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: commerce-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes:
      - "C:/Users/Ozgur PC/Desktop/minio_backup:/data"

volumes:
  postgres_data:
  redis_data:
