services:
  db:
    image: postgres:16
    container_name: commerce-db
    environment:
      POSTGRES_USER: postgres        # ✅ postgres
      POSTGRES_PASSWORD: postgres    # ✅ postgres
      POSTGRES_DB: commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d commerce" ]  # ✅ postgres
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: commerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: commerce-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  minio_data: